#=============================================================================
# Midas Server
# Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
# All rights reserved.
# For more information visit http://www.kitware.com/.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#=============================================================================

---
language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update -n
  - if [[ $TRAVIS_PULL_REQUEST = false ]]; then composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN; fi
  - if [[ $TRAVIS_PHP_VERSION = 5.3 ]]; then sed -i '/uuid-console/d' composer.json; fi
  - if [[ $TRAVIS_PHP_VERSION = hhvm || $TRAVIS_PHP_VERSION = 7 ]]; then sed -i '/ext-xdebug/d' composer.json; fi

install:
  - travis_retry composer install -n --prefer-dist

before_script:
  - cp tests/ci/travis/mysql.ini tests/configs/mysql.ini && mysql -u root -e 'create database midas_test;'
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then cp tests/ci/travis/pgsql.ini tests/configs/pgsql.ini && psql -U postgres -c 'create database midas_test;'; fi
  - cp tests/ci/travis/sqlite.ini tests/configs/sqlite.ini && touch midas_test.db

script:
  - mkdir _test && cd _test
  - cmake ..
  - ctest -E 'GeolocationLookup|PerformCleanup' -j2 -V .
