language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - cp tests/travis/mysql.ini tests/configs/mysql.ini && cp tests/travis/pgsql.ini tests/configs/pgsql.ini
  - mysql -u root -e 'create database midas_test;'
  - psql -U postgres -c 'create database midas_test;'

script:
  - mkdir _test && cd _test
  - cmake ..
  - ctest -j2 -V .
